---
provisioner:
  name: chef_zero
  require_chef_omnibus: latest

driver:
  name: vagrant
  customize:
    memory: 1024

platforms:
  - name: centos-6.4
  - name: ubuntu-12.04

suites:
- name: control
  run_list:
    - recipe[ktc-testing]
    - recipe[etcd::compile_time]
    - recipe[ktc-monitor::client]
    - recipe[ktc-database]
    - recipe[ktc-messaging]
    - recipe[ktc-memcached]
    - recipe[ktc-controller]
  attributes:
    etcd:
      servers:
        - localhost
    ha_disabled: true
    mysql:
      allow_remote_root: true
      root_network_acl: '%'
      server_root_password: 'root'
      server_debian_password: 'debian'
      server_repl_password: 'repl'
    openstack:
      availability_zone: vagrant.dev
      developer_mode: true
      compute:
        driver: 'fake.FakeDriver'
        identity_service_chef_role: 'ktc-controller'
      endpoints:
        compute-metadata-api:
          host: 'xxx.xxx.xxx.xxx'
          port: '8775'
      network:
        ng_l3:
          setup_entities: false
    authorization:
      sudo:
        users:
          - vagrant
        passwordless: true

